# -*- coding: utf-8 -*-
"""Python Introduction for Data Analysis MySkill

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1o7gthjtdSWJa1M1PDZLpGAODxF7O1ask

# IMPORT DATASET
"""

# import dataset use library pandas

import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

df = pd.read_csv('/content/drive/My Drive/Course/Datasets/super-store.csv')

"""# LOAD DATASET"""

# display dataset 5 row first

df.head()

"""# TAIL DATASET"""

# display dataset 5 row last

df.tail()

"""# SAMPLE DATASET"""

# display dataset 5 row random

df.sample(5)

"""# CONVERT DATASET"""

# convert dataset to spreadsheet

from google.colab import sheets

sheet = sheets.InteractiveSheet(df=df)

"""# INFO DATASET"""

# check info dataset

df.info()

"""# VISUALIZATION DATASET"""

# import chart use matplotlib

import matplotlib.pyplot as plt

# display chart from sales

df['Sales'].plot()
plt.title('Sales')

# display chart from quantity

df['Quantity'].plot()
plt.title('Quantity')

# display chart from discount

df['Discount'].plot()
plt.title('Discount')

# display chart from profit

df['Profit'].plot()
plt.title('Profit')